"""
This type stub file was generated by pyright.
"""

from .renderer import Renderer

"""Contains the BackgroundRenderer class."""
class BackgroundRenderer(Renderer):
    """BackgroundRenderer for visualizing a background image.

    Parameters
    ----------
    parent : Renderer
        The parent renderer for the background renderer.
    image_path : str
        Path to the image to use as a background.
    scale : float, default: 1
        Scaling factor for the background image.
    view_port : tuple[float], optional
        Viewport for the background renderer.

    """
    def __init__(self, parent, image_path, scale=..., view_port=...) -> None:
        """Initialize BackgroundRenderer with an image."""
        ...
    
    def resize(self, *args): # -> None:
        """Resize a background renderer.

        Parameters
        ----------
        *args : tuple
            Ignored arguments.

        """
        ...
    


