"""
This type stub file was generated by pyright.
"""

from ._filters import *
from ._fourier import *
from ._interpolation import *
from ._measurements import *
from ._morphology import *

"""This is the 'bare' ndimage API.

This --- private! --- module only collects implementations of public ndimage API
for _support_alternative_backends.
The latter --- also private! --- module adds delegation to CuPy etc and
re-exports decorated names to __init__.py
"""
__all__ = [s for s in dir() if not s.startswith('_')]
