"""
This type stub file was generated by pyright.
"""

__all__ = ['fourier_gaussian', 'fourier_uniform', 'fourier_ellipsoid', 'fourier_shift']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

