"""
This type stub file was generated by pyright.
"""

__all__ = ['label', 'find_objects', 'labeled_comprehension', 'sum', 'mean', 'variance', 'standard_deviation', 'minimum', 'maximum', 'median', 'minimum_position', 'maximum_position', 'extrema', 'center_of_mass', 'histogram', 'watershed_ift', 'sum_labels']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

