"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import SupportsIndex, TypeAlias

_Shape: TypeAlias = tuple[int, ...]
_ShapeLike: TypeAlias = SupportsIndex | Sequence[SupportsIndex]
