name: lathe

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=lathe
        - APP_USER=dev
        - PYTHON_VERSION=3.12
      secrets:
        - app_user_password
    # image: northernscott/lathe:latest
    stdin_open: true
    tty: true
    container_name: lathe-app
    restart: unless-stopped
    volumes:
      - type: bind
        source: ../.home
        target: /home/dev
    develop:
      watch:
        - action: sync
          path: ../src
          target: /opt/lathe
    secrets:
      - app_user_password

secrets:
  app_user_password:
    file: app_user_password.txt
