name: lathe

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=lathe
        - APP_USER=dev
        - PYTHON_VERSION=3.12
      secrets:
        - app_user_password
    # image: northernscott/lathe:latest
    stdin_open: true
    tty: true
    container_name: lathe-app
    hostname: lathe-app
    restart: unless-stopped
    volumes:
      - type: volume
        source: home-data
        target: /home/dev # /home/<APP_USER> must match the APP_USER build argument.
    networks:
      - lathe-bridge
    develop:
      watch:
        - action: sync
          path: ../src
          target: /opt/lathe # /opt/<APP_NAME> must match the APP_NAME build argument.
    secrets:
      - app_user_password

volumes:
  home-data:
    name: "lathe-app-home-data"

networks:
  lathe-bridge:
    driver: bridge
    name: "lathe-bridge"

secrets:
  app_user_password:
    file: app_user_password.txt
