name: lathe

services:
  app:
    image: northernscott/lathe:latest
    build:
      context: ..
      dockerfile: .docker/.
    stdin_open: true
    tty: true
    container_name: lathe-app
    restart: unless-stopped
    environment:
      APP_NAME: "lathe"
      NODE_ENV: "development"
      USER: "dev"
      PASSWORD: "dev"
      PYTHON_VERSION: 3.12
    volumes:
      - type: bind
        source: ../.home
        target: /home/dev
    develop:
      watch:
      - action: sync
        path: ../src
        target: /opt/lathe