"""
This type stub file was generated by pyright.
"""

__all__ = ['KDTree', 'Rectangle', 'cKDTree', 'distance_matrix', 'minkowski_distance', 'minkowski_distance_p']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

