"""
This type stub file was generated by pyright.
"""

"""
Routines for removing redundant (linearly dependent) equations from linear
programming equality constraints.
"""
def bg_update_dense(plu, perm_r, v, j): # -> tuple[Any, Any]:
    ...

