"""
This type stub file was generated by pyright.
"""

__all__ = ['RootResults', 'bisect', 'brenth', 'brentq', 'newton', 'ridder', 'toms748']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

