"""
This type stub file was generated by pyright.
"""

from ._differentiate import *
from scipy._lib._testutils import PytestTester

"""
==============================================================
Finite Difference Differentiation (:mod:`scipy.differentiate`)
==============================================================

.. currentmodule:: scipy.differentiate

SciPy ``differentiate`` provides functions for performing finite difference
numerical differentiation of black-box functions.

.. autosummary::
   :toctree: generated/

   derivative
   jacobian
   hessian

"""
__all__ = ['derivative', 'jacobian', 'hessian']
test = ...
