"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple

"""
This type stub file was generated by pyright.
"""
class VersionInfo(NamedTuple):
    """Version information as a named tuple."""
    major: int
    minor: int
    micro: int
    ...


def VTKVersionInfo():
    """Return the vtk version as a namedtuple.

    Returns
    -------
    VersionInfo
        Version information as a named tuple.

    """
    ...

vtk_version_info = ...
