"""
This type stub file was generated by pyright.
"""

import pytest

"""
This type stub file was generated by pyright.
"""
@pytest.fixture(autouse=True)
def autoclose_plotters():
    """Close all plotters."""
    ...

@pytest.fixture(autouse=True)
def reset_gloal_theme():
    """Reset global_theme."""
    ...

