"""
This type stub file was generated by pyright.
"""

__all__ = ['qr', 'qr_multiply', 'rq', 'get_lapack_funcs']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

