"""
This type stub file was generated by pyright.
"""

__all__ = ['MatrixRankWarning', 'SuperLU', 'factorized', 'spilu', 'splu', 'spsolve', 'spsolve_triangular', 'use_solver', 'test']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

