"""
This type stub file was generated by pyright.
"""

__all__ = ['fftshift', 'ifftshift', 'fftfreq', 'rfftfreq', 'next_fast_len']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

