"""
This type stub file was generated by pyright.
"""

__all__ = ['dct', 'idct', 'dst', 'idst', 'dctn', 'idctn', 'dstn', 'idstn']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

