"""
This type stub file was generated by pyright.
"""

import warnings
from .._utils import _inspect
from .._utils._inspect import formatargspec, getargspec
from . import py3k
from .py3k import *

"""
Compatibility module.

This module contains duplicated code from Python itself or 3rd party
extensions, which may be included for the following reasons:

  * compatibility
  * we may only need a small subset of the copied library/module

This module is deprecated since 1.26.0 and will be removed in future versions.

"""
__all__ = []
