"""
This type stub file was generated by pyright.
"""

__all__ = ['BivariateSpline', 'InterpolatedUnivariateSpline', 'LSQBivariateSpline', 'LSQSphereBivariateSpline', 'LSQUnivariateSpline', 'RectBivariateSpline', 'RectSphereBivariateSpline', 'SmoothBivariateSpline', 'SmoothSphereBivariateSpline', 'UnivariateSpline']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

