"""
This type stub file was generated by pyright.
"""

__all__ = ['BSpline', 'bisplev', 'bisplrep', 'insert', 'spalde', 'splantider', 'splder', 'splev', 'splint', 'splprep', 'splrep', 'sproot']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

