"""
This type stub file was generated by pyright.
"""

__all__ = ['CloughTocher2DInterpolator', 'GradientEstimationWarning', 'LinearNDInterpolator', 'NDInterpolatorBase', 'estimate_gradients_2d_global']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

