"""
This type stub file was generated by pyright.
"""

__all__ = ['BarycentricInterpolator', 'KroghInterpolator', 'approximate_taylor_polynomial', 'barycentric_interpolate', 'krogh_interpolate']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

