"""
This type stub file was generated by pyright.
"""

from typing import Tuple, Union
from pyvista.core import _vtk_core as _vtk
from ._array_like import NumberType, _ArrayLike, _ArrayLike1D, _ArrayLike2D

"""
This type stub file was generated by pyright.
"""
Number = Union[int, float]
VectorLike = _ArrayLike1D[NumberType]
MatrixLike = _ArrayLike2D[NumberType]
ArrayLike = _ArrayLike[NumberType]
TransformLike = Union[MatrixLike[float], _vtk.vtkMatrix3x3, _vtk.vtkMatrix4x4, _vtk.vtkTransform]
BoundsLike = Tuple[Number, Number, Number, Number, Number, Number]
CellsLike = Union[MatrixLike[int], VectorLike[int]]
CellArrayLike = Union[CellsLike, _vtk.vtkCellArray]
_ArrayLikeOrScalar = Union[NumberType, ArrayLike[NumberType]]
