"""
This type stub file was generated by pyright.
"""

import importlib as _importlib
import warnings
from numpy import __version__ as __numpy_version__
from scipy.__config__ import show as show_config
from scipy.version import version as __version__
from . import _distributor_init
from scipy._lib import _pep440
from scipy._lib._ccallback import LowLevelCallable
from scipy._lib._testutils import PytestTester

"""
SciPy: A scientific computing package for Python
================================================

Documentation is available in the docstrings and
online at https://docs.scipy.org.

Subpackages
-----------
Using any of these subpackages requires an explicit import. For example,
``import scipy.cluster``.

::

 cluster                      --- Vector Quantization / Kmeans
 constants                    --- Physical and mathematical constants and units
 datasets                     --- Dataset methods
 differentiate                --- Finite difference differentiation tools
 fft                          --- Discrete Fourier transforms
 fftpack                      --- Legacy discrete Fourier transforms
 integrate                    --- Integration routines
 interpolate                  --- Interpolation Tools
 io                           --- Data input and output
 linalg                       --- Linear algebra routines
 ndimage                      --- N-D image package
 odr                          --- Orthogonal Distance Regression
 optimize                     --- Optimization Tools
 signal                       --- Signal Processing Tools
 sparse                       --- Sparse Matrices
 spatial                      --- Spatial data structures and algorithms
 special                      --- Special functions
 stats                        --- Statistical Functions

Public API in the main SciPy namespace
--------------------------------------
::

 __version__       --- SciPy version string
 LowLevelCallable  --- Low-level callback function
 show_config       --- Show scipy build configuration
 test              --- Run scipy unittests

"""
np_minversion = ...
np_maxversion = ...
if (_pep440.parse(__numpy_version__) < _pep440.Version(np_minversion) or _pep440.parse(__numpy_version__) >= _pep440.Version(np_maxversion)):
    ...
test = ...
submodules = ...
__all__ = submodules + ['LowLevelCallable', 'test', 'show_config', '__version__']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> ModuleType | Any:
    ...

