"""
This type stub file was generated by pyright.
"""

__all__ = ['isspmatrix_lil', 'lil_array', 'lil_matrix']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

