"""
This type stub file was generated by pyright.
"""

from typing import Literal, TYPE_CHECKING, Union
from numpy import dtype, float32, float64, int16, int32, int64, int8, uint16, uint32, uint64, uint8

__all__ = ["ndarray", "Device", "Dtype"]
Device = Literal["cpu"]
if TYPE_CHECKING or sys.version_info >= (3, 9):
    Dtype = dtype[Union[int8, int16, int32, int64, uint8, uint16, uint32, uint64, float32, float64,]]
else:
    ...
